name: car_m
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.3.0'


dependencies:
  geocoding: ^2.1.0
  location: ^4.4.0
  google_maps_flutter: ^2.2.8
  provider: ^6.0.5
  bloc_concurrency: ^0.2.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  image_picker: ^0.8.5
  intl_utils: ^2.8.2
  google_fonts: ^4.0.3
  flutter_svg: ^1.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  html: any
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.20
  dio: ^5.1.1
  json_annotation: ^4.8.0
  get: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1

flutter:
  generate: true
  assets:
    - assets/images/bitmap/
    - assets/images/svg/
  uses-material-design: true